// ==UserScript==
// @name         AFK™.lol Bypasser
// @namespace    https://afk.lol/
// @version      1.1.7
// @description  Bypass Links
// @author       afk.l0l
// @icon         https://i.ibb.co/ks0qXqqY/B57-FBD3-E-489-E-4-F0-D-A5-C0-08017-DA44-C4-E.png
// @match        https://mboost.me/*
// @match        https://deltaios-executor.com/*
// @match        https://krnl-ios.com/*
// @match        https://auth.platoboost.app/*
// @match        https://auth.platoboost.net/*
// @match        https://loot-link.com/*
// @match        https://lootlink.org/*
// @match        https://lootlinks.co/*
// @match        https://lootdest.info/*
// @match        https://lootdest.org/*
// @match        https://lootdest.com/*
// @match        https://links-loot.com/*
// @match        https://loot-links.com/*
// @match        https://best-links.org/*
// @match        https://lootlinks.com/*
// @match        https://loot-labs.com/*
// @match        https://lootlabs.com/*
// @match        https://pandadevelopment.net/*
// @match        https://krnl.cat/*
// @match        https://lockr.so/*
// @match        https://link-unlock.com/*
// @match        https://direct-link.net/*
// @match        https://link-target.net/*
// @match        https://link-to.net/*
// @match        https://link-center.net/*
// @match        https://link-hub.net/*
// @match        https://up-to-down.net/*
// @match        https://linkvertise.com/*
// @match        https://sub2get.com/*
// @match        https://sub4unlock.com/*
// @match        https://sub2unlock.net/*
// @match        https://sub2unlock.com/*
// @match        https://rekonise.com/*
// @match        https://rkns.link/*
// @match        https://rekonise.org/*
// @match        https://overdrivehub.xyz/*
// @grant        GM_addStyle
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_openInTab
// @grant        GM_info
// @grant        GM_xmlhttpRequest
// @grant        GM_notification
// @connect      *
// @require      https://raw.githubusercontent.com/VortexBypass/AFK-.lol-Bypass/refs/heads/main/AFKdotlol.yes.js
// @updateURL    https://raw.githubusercontent.com/VortexBypass/AFK-.lol-Bypass/refs/heads/main/AFKdotlol.meta.js
// @downloadURL  https://raw.githubusercontent.com/VortexBypass/AFK-.lol-Bypass/refs/heads/main/AFKdotlol.user.js
// @run-at       document-start
// ==/UserScript==
